hswno/kofradia

- public/ff/index.php
Satte ned ventetiden for å kjøpe energi og endret pris for det dyreste alternativet
> Ventetid og kostnad for energi

- public/ff/index.php
Endret ventetid for å oppgradere våpen fra 48 timer til 24 timer.
> Ventetid for å oppgradere våpen

- app/pages/angrip.php
Utvidet angrepstiden fra 20-22 til 18-22.
> Utvide angrepstid

- public/oppdrag.php
Slik at teksten står i samsvar til de nylige endringene.
> Rettet på tekst

- app/pages/kriminalitet.php
Tekstforklaringen til kriminalitet var feil.
> Rettet på tekstforklaring

- app/pages/min_side_player.php
Fremdrift vil nå vises uten å holde over den grønne linjen.
> La til fremdrift på prestasjoner

- app/views/game/utpressing/log.php
Var en feil på siste utpressinger siden som gjorde at man ikke kunne se sidetallene.
> Fikset sidetall på logsiden for utpressinger

- public/registrer.php
Det er snart fem år siden vi het SM.
> Skiftet SM til Kofradia

- public/rss/index.php
Svar og tråder linket til feil side.
> Byttet om på svar og tråder link

- app/pages/angrip.php
Oppdaterte stengetid for jul og nyttårsaften til å være uavhengig av år.
> Stengetid jul

- app/src/Kofradia/Polls/PollOption.php
Den burde fikse den ene feilen i #197
> Fikset feil når man avgir stemme på en avstemning.

- app/pages/fengsel.php
> Typo for mod+

- public/crewet.php
I hovedsak fordi "ressurser" høres ut som et gode man har, fremfor en crewstilling man har om man skal være konsekvent andre veien med alle stillinger
> Konsekvente navn

- app/extra/class.oppdrag.php
- app/scheduler/rank_bonus.php
- app/scheduler/vervebonus.php
> vervebonus og rankbonus teller nå ikke til rankeoppdraget

- public/themes/sm/default.php
> Burde fikse feilen med avstemning forummalen

- app/extra/class.ff.php
> Trekk tilbake invitasjon når FF blir oppløst

- app/scheduler/vervebonus.php
> 20% vervebonus i desember

- app/pages/banken.php
> Fixed confusing bank transfer log

- public/registrer.php
avbrytet -> avbrutt
"og ta evt." -> "eller ta"
"ikke glem og les" -> "ikke glem å lese"
"i følge" -> ifølge
en -> én
> skrivefeils

- app/extra/class.crewlog.php
- app/pages/min_side_player.php
> Endring av profilbilder til andre spillere kommer opp i crewloggen

- app/pages/bydeler.php
- public/ff/index.php
fixes #204 
https://i.imgur.com/qsCs7TF.png
> La til aktivering og deaktivering av broderskapkonkurranser

- public/themes/sm/default.php
la også til en bindestrek i Esc-knappen
> fjernet quakenet fra bunnen av siden

- public/statistikk.php
> La til bleed_num på statistikksiden.

- app/pages/bydeler.php
- app/views/helpers/confirm.html.twig
- public/ff/index.php
Laget en ny twig template for bekreftelse bokser og brukte den.
> La til bekreftelse for deaktivering og oppretting av broderskapkonkurranse

- app/extra/class.antibot.php
- app/pages/angrip.php
- app/pages/antibot.php
- app/pages/gta.php
- app/pages/kriminalitet.php
- app/pages/lotto.php
- app/src/Kofradia/Controller/Game/Utpressing.php
slik at alle aktivitetene teller opp mot samme globale antibot.
fixes #174 
Verdien for `const ANTIBOT_SPAN = 9`  er testet av meg og @Dreamfreeze. Er mulig den må forandres på.
> Byttet ut alle antibotene med en default antibot

- app/pages/antibot.php
Da burde den virke for både "default" og "kuler" som har egen sjekk
> Fikset så antibot-siden henter antibot fra name variabelen

- public/crew/avstemninger.php
Ved sletting av avstemning blir man sendt tilbake den samme avstemningen man sletter. La til redirect til hovedmenyen etter sletting av avstemning.
https://i.imgur.com/xRPDKkR.png
> fix redirect så det ikke kommer feil etter slett

- app/extra/class.player.php
As suggested in part of #252, all position changes within top 15 ranklist will be announced in live feed
> Changed position change to top 15 rather than 10

- public/ff/index.php
> Added a check so that you can't place yourself in bomberom while on an active oppdrag.

- app/views/helpers/new_broderskap.html.twig
- public/ff/index.php
you create a new broderskap.
fixes #240
> Changed so that you can choose which competition you want to enter when

- app/extra/class.lotto.php
Also changed the pot distribution slightly and a mini-typo
> Changed lotto ticket price to accomodate most users after a recent poll
